### ISSUE TITLE
Custom datamanager + tyro error

### ISSUE THREAD

**Issue by myaldiz** [brentyi/tyro#20]
Hi there!

I asked a question in discord channel, I want to just follow it up here, my question was following:

> I want to implement new datamodules but don't want to include them in the directory of nerfstudio, but rather want to keep them externally. I copied the train.py code, and add my own configs to method_configs dictionary. I call tyro.cli with modified AnnotatedBaseConfigUnion, but tyro gives AssertionError. I realized I have to modify datamanagers.py and my new dataparserconfig but I want to avoid modifying any code in nerfstudio. What is the correct approach to achieve this?

Here is my code:
```python

import pathlib
import sys

current_path = pathlib.Path(__file__).parent.resolve()
sys.path.append(str(current_path.parent / "dependencies/nerfstudio/scripts"))
from scripts.train import main

from dataclasses import dataclass, field
from pathlib import Path
from typing import Type

import tyro
# from nerfstudio.cameras.camera_optimizers import CameraOptimizerConfig
from nerfstudio.configs.base_config import Config
from nerfstudio.data.datamanagers import VanillaDataManagerConfig
from nerfstudio.data.dataparsers.blender_dataparser import BlenderDataParserConfig, Blender
# from nerfstudio.data.dataparsers.friends_dataparser import FriendsDataParserConfig
# from nerfstudio.data.dataparsers.nerfstudio_dataparser import NerfstudioDataParserConfig
from nerfstudio.engine.optimizers import AdamOptimizerConfig, RAdamOptimizerConfig
from nerfstudio.models.base_model import VanillaModelConfig
from nerfstudio.models.vanilla_nerf import NeRFModel
from nerfstudio.pipelines.base_pipeline import VanillaPipelineConfig
# from nerfstudio.pipelines.dynamic_batch import DynamicBatchPipelineConfig
from nerfstudio.configs.config_utils import convert_markup_to_ansi
from nerfstudio.configs.method_configs import method_configs, descriptions
from nerfstudio.data.dataparsers.base_dataparser import DataParserConfig

@dataclass
class TempDataParserConfig(DataParserConfig):
    _target: Type = field(default_factory=lambda: Blender)
    """target class to instantiate"""
    data: Path = Path("data/blender/lego")
    """Directory specifying location of data."""
    scale_factor: float = 1.0
    """How much to scale the camera origins by."""
    alpha_color: str = "white"
    """alpha color of background"""

def entrypoint():
    """Entrypoint for use with pyproject scripts."""
    # Choose a base configuration and override values.
    tyro.extras.set_accent_color("bright_yellow")

    # Add hyperlight models to the method configs and descriptions
    descriptions["temp-model"] = "Temp-model"
    method_configs["temp-model"] = Config(
        method_name="vanilla-nerf",
        pipeline=VanillaPipelineConfig(
            datamanager=VanillaDataManagerConfig(
                dataparser=TempDataParserConfig(),
                # dataparser=BlenderDataParserConfig(),
                train_num_images_to_sample_from = 8,
                train_num_times_to_repeat_images = 4,
                eval_num_images_to_sample_from = 2,
                eval_num_times_to_repeat_images = 1,
            ),
            model=VanillaModelConfig(_target=NeRFModel),
        ),
        optimizers={
            "fields": {
                "optimizer": RAdamOptimizerConfig(lr=5e-4, eps=1e-08),
                "scheduler": None,
            }
        },
    )

    AnnotatedBaseConfigUnion = tyro.conf.SuppressFixed[  # Don't show unparseable (fixed) arguments in helptext.
    tyro.extras.subcommand_type_from_defaults(defaults=method_configs, descriptions=descriptions)
    ]
    main(
        tyro.cli(
            AnnotatedBaseConfigUnion,
            description=convert_markup_to_ansi(__doc__),
        )
    )


if __name__ == "__main__":
    entrypoint()
```

Here is the error it produces:
```bash
Traceback (most recent call last):
  File "/host/scripts/train_temp.py", line 83, in <module>
    entrypoint()
  File "/host/scripts/train_temp.py", line 75, in entrypoint
    tyro.cli(
  File "/opt/conda/lib/python3.9/site-packages/tyro/_cli.py", line 125, in cli
    _cli_impl(
  File "/opt/conda/lib/python3.9/site-packages/tyro/_cli.py", line 275, in _cli_impl
    parser_definition = _parsers.ParserSpecification.from_callable_or_type(
  File "/opt/conda/lib/python3.9/site-packages/tyro/_parsers.py", line 99, in from_callable_or_type
    subparsers_attempt = SubparsersSpecification.from_field(
  File "/opt/conda/lib/python3.9/site-packages/tyro/_parsers.py", line 383, in from_field
    subparser = ParserSpecification.from_callable_or_type(
  File "/opt/conda/lib/python3.9/site-packages/tyro/_parsers.py", line 129, in from_callable_or_type
    nested_parser = ParserSpecification.from_callable_or_type(
  File "/opt/conda/lib/python3.9/site-packages/tyro/_parsers.py", line 129, in from_callable_or_type
    nested_parser = ParserSpecification.from_callable_or_type(
  File "/opt/conda/lib/python3.9/site-packages/tyro/_parsers.py", line 99, in from_callable_or_type
    subparsers_attempt = SubparsersSpecification.from_field(
  File "/opt/conda/lib/python3.9/site-packages/tyro/_parsers.py", line 357, in from_field
    assert default_name is not None
AssertionError
```

Would appreciate your help to achieve such functionality

**Comment by brentyi** [comment]
As a shorter hack, replacing the last few lines of your script with this will also work:
```python
if __name__ == "__main__":
    from nerfstudio.data.datamanagers import base_datamanager
    from typing import Any
    base_datamanager.AnnotatedDataParserUnion = Any

    entrypoint()
```

**Comment by jianglongye** [comment]
I also encountered the same error when I just wanted to change the default value of `nerfstudio` built-in `dataparser`. I was just wondering if we could make type checking more flexible by only checking types instead of types with specific default values?

**Comment by jingyibo123** [comment]
Same issue here.

Instead of directly modifying the default values defined in `XXXDataparser` or `XXXDatamanager`, one usually defines a `method_configs` instance overwriting the default with arbitrary value.

What's weird is this approach works with nerfstudio's datamanager, but not the dataparser (same as @jianglongye )

**Comment by brentyi** [comment]
Thanks for flagging @jingyibo123  and sorry for missing your comment @jianglongye!

I'm currently swamped can revisit this after March 10~15ish, if you don't find a fix before then and are still interested in this do you mind pinging me again?

One option that might work is to replace this error:
https://github.com/brentyi/tyro/blob/47a211aaa0649f58892934522ac2e0649453bb58/tyro/_parsers.py#L375-L381
with a warning, and then append the type of the provided default to the parsed union type.

There's likely also something we can do upstream in nerfstudio to loosen the static type.

**Comment by brentyi** [comment]
The latest release replaces this assertion error with a warning. If you're still having problems with this feel free to re-open!

**Comment by jingyibo123** [comment]
Confirmed the exception/error is gone ~
Thanks
