### ISSUE TITLE
conf.Suppress cause no default value error on nested configs

### ISSUE THREAD

**Issue by Goulustis** [brentyi/tyro#216]
I have a minimal file `dev.py` file that produce the error here
```python
import tyro
from dataclasses import dataclass, field

@dataclass
class Bconfig:
    b: int = 1

@tyro.conf.configure(tyro.conf.Suppress)  # line in question
@dataclass
class Aconfig:
    a:str = "hello"
    b_conf: Bconfig = field(default_factory=Bconfig)


if __name__ == "__main__":
    tyro.cli(Aconfig)
```

When I run `python dev.py -h`
I encounter missing default value for b_conf despite having default values:
```
Traceback (most recent call last):
  File "/home/boss/projects/scratch/dev.py", line 16, in <module>
    tyro.cli(Aconfig)
  File "/home/boss/miniforge3/envs/chain/lib/python3.10/site-packages/tyro/_cli.py", line 207, in cli
    output = _cli_impl(
  File "/home/boss/miniforge3/envs/chain/lib/python3.10/site-packages/tyro/_cli.py", line 402, in _cli_impl
    parser_spec = _parsers.ParserSpecification.from_callable_or_type(
  File "/home/boss/miniforge3/envs/chain/lib/python3.10/site-packages/tyro/_parsers.py", line 82, in from_callable_or_type
    f, type_from_typevar, field_list = _fields.field_list_from_callable(
  File "/home/boss/miniforge3/envs/chain/lib/python3.10/site-packages/tyro/_fields.py", line 303, in field_list_from_callable
    field_list = list(map(lambda field: field.add_markers(parent_markers), field_list))
  File "/home/boss/miniforge3/envs/chain/lib/python3.10/site-packages/tyro/_fields.py", line 303, in <lambda>
    field_list = list(map(lambda field: field.add_markers(parent_markers), field_list))
  File "/home/boss/miniforge3/envs/chain/lib/python3.10/site-packages/tyro/_fields.py", line 147, in add_markers
    return dataclasses.replace(
  File "/home/boss/miniforge3/envs/chain/lib/python3.10/dataclasses.py", line 1453, in replace
    return obj.__class__(**changes)
  File "<string>", line 13, in __init__
  File "/home/boss/miniforge3/envs/chain/lib/python3.10/site-packages/tyro/_fields.py", line 85, in __post_init__
    raise _instantiators.UnsupportedTypeAnnotationError(
tyro._instantiators.UnsupportedTypeAnnotationError: Field b_conf is missing a default value!
```

The `python dev.py -h` will run fine if the tyro.conf.Suppress decorator is not there.
Any help would be greatly appreciated!

**Comment by Goulustis** [comment]
resolved

ChatGPT generated the wrong thing and I overlooked it... I should have used
`@tyro.conf.configure(tyro.conf.Suppress)`
