### ISSUE TITLE
KeyError with prefix "_" for nested config

### ISSUE THREAD

**Issue by DerKleineLi** [brentyi/tyro#77]
Hi there, I got error when trying to build the config with private configs indicated by a prefix underscore.

To reproduce the error:
```python
from dataclasses import dataclass, field
import tyro
@dataclass
class PrivateConfig:
    pass
@dataclass
class BaseConfig:
    _private: PrivateConfig = field(default_factory=lambda: PrivateConfig())
@dataclass
class Level1(BaseConfig):
    pass
@dataclass
class Level2(BaseConfig):
    child: Level1 = field(default_factory=lambda: Level1())
@dataclass
class Level3(BaseConfig):
    child: Level2 = field(default_factory=lambda: Level2())
if __name__ == "__main__":
    tyro.cli(Level3)
```
The output:
```text
Traceback (most recent call last):
  File "/home/hli/Documents/sdfli/tmp.py", line 32, in <module>
    tyro.cli(Level3)
  File "/home/hli/miniconda3/envs/sdfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 187, in cli
    output = _cli_impl(
  File "/home/hli/miniconda3/envs/sdfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 449, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/home/hli/miniconda3/envs/sdfstudio/lib/python3.8/site-packages/tyro/_calling.py", line 122, in call_from_args
    value, consumed_keywords_child = call_from_args(
  File "/home/hli/miniconda3/envs/sdfstudio/lib/python3.8/site-packages/tyro/_calling.py", line 122, in call_from_args
    value, consumed_keywords_child = call_from_args(
  File "/home/hli/miniconda3/envs/sdfstudio/lib/python3.8/site-packages/tyro/_calling.py", line 132, in call_from_args
    subparser_def = parser_definition.subparsers_from_prefix[
KeyError: 'child.child._private'
```

The error is resolved by replacing `_private` to `private`, and it only happens when `level >= 3`. I want to use an underscore at the beginning to indicate the private variables. Is there a solution for that?

Thank you!

**Comment by brentyi** [comment]
Hi @DerKleineLi!

Thanks for the succinct reproduction instructions. I just pushed a patch, which should be available as version `0.5.10` on PyPI shortly.
